apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
      - name: container1
        image: gcr.io/myproject2203/container1:latest
        ports:
        - containerPort: 6000
        env:
        - name: PV_DIR
          value: "/mnt/data"
        - name: CONTAINER2_BASE_URL
          value: "http://container2-service:80"
        volumeMounts:
        - name: shared-data
          mountPath: /mnt/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: data-pvc
