steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/container1:latest', './container1']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/container1:latest']
  
  # Set up kubectl and authenticate with GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'kubernetes-assignment-cluster'
      - '--zone'
      - 'us-central1-a'
    id: 'Set up kubectl'

  # Delete validating webhook configuration
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'delete'
      - 'validatingwebhookconfiguration'
      - 'gmp-operator.gmp-system.monitoring.googleapis.com'
      - '--ignore-not-found=true'
    id: 'Delete GMP validating webhooks'
    
  # Delete mutating webhook configuration
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'delete'
      - 'mutatingwebhookconfiguration'
      - 'gmp-operator.gmp-system.monitoring.googleapis.com'
      - '--ignore-not-found=true'
    id: 'Delete GMP mutating webhooks'

  # Deploy the latest image to GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'kubectl'
      - 'apply'
      - '-f'
      - 'container1/k8s/container1_deployment.yaml'
    id: 'Deploy container1 to GKE'

images:
  - 'gcr.io/$PROJECT_ID/container1:latest'

options:
  logging: CLOUD_LOGGING_ONLY