steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/container1/container1:latest', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/container1/container1:latest']
  
  # Deploy container image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/container1'
      - 'container1=us-central1-docker.pkg.dev/${PROJECT_ID}/container1/container1:latest'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=container1-cluster'

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/container1/container1:latest'

options:
  logging: CLOUD_LOGGING_ONLY